version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: missingpets-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - missingpets-network

  backend:
    build: ./backend
    container_name: missingpets-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/missingpets?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - mongodb
    networks:
      - missingpets-network
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    container_name: missingpets-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - missingpets-network

  nginx:
    image: nginx:alpine
    container_name: missingpets-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - missingpets-network

volumes:
  mongodb_data:

networks:
  missingpets-network:
    driver: bridge